CREATE TABLE TRANSFERS (
	ID varchar(100) UNIQUE NOT NULL,
    ACCOUNT_ORIGIN_ID varchar(100) NOT NULL,
    ACCOUNT_DESTINATION_ID varchar(100) NOT NULL,
    AMOUNT FLOAT NOT NULL,
    CREATED_AT DATETIME NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (ACCOUNT_ORIGIN_ID) REFERENCES ACCOUNTS(ID),
    FOREIGN KEY (ACCOUNT_DESTINATION_ID) REFERENCES ACCOUNTS(ID)
);